# This file is used to configure your project.
# Read more about the various options under:
# https://setuptools.pypa.io/en/latest/userguide/declarative_config.html
# https://setuptools.pypa.io/en/latest/references/keywords.html

[metadata]
name = plotomatic
description = AI-powered story planning assistant
author = Matt Williamson
author_email = matt@aimatt.com
license = MIT
license_files = LICENSE.txt
long_description = file: README.md
long_description_content_type = text/markdown

[options]
zip_safe = False
include_package_data = True
package_dir =
    =src
python_requires = >=3.10

[tool:pytest]
addopts =
    --cov plotomatic --cov-report term-missing
    --verbose
testpaths = tests
