models:
  - type: main
    engine: ollama
    model: nemotron:70b


custom_schema:
  path: story_dialog_schema.json  # Path to your JSON schema file


rails:
  input:
    flows:
      - self_check_input

  output:
    flows:
      - validate_and_retry_output



retry:
  max_attempts: 3  # Maximum number of retry attempts
  delay: 1         # Delay in seconds between attempts


prompts:
  - task: self_check_input
    content: |
      Your task is to check if the user message below complies with the policy for talking with the AI Enterprise bot.
      Policy for user messages:
      - should not contain explicit content
      - should not use abusive language

  - task: self_check_output
    content: |
      Your task is to check if the bot message below complies with the policy.
      Policy for bot messages:
      - messages should not contain explicit content or abusive language.
